AWSTemplateFormatVersion: 2010-09-09
Resources:
  DynamodbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TableOfBooks
      AttributeDefinitions:
        - AttributeName: "category"
          AttributeType: "S"
        - AttributeName: "title"
          AttributeType: "S"



      KeySchema:
        - AttributeName: "category"
          KeyType: "HASH"
        - AttributeName: "title"
          KeyType: "RANGE"

      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
    DependsOn:
      - DynamoDBQueryPolicy
  DynamoDBQueryPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: DynamoDBQueryPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "dynamodb:Query"

            Resource: "*"
      Roles:
        - Ref: "dynamodbTableQueryRole"

  dynamodbTableQueryRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "dynamodb.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"